ALTER TABLE posts ADD COLUMN visibility VARCHAR(16) NOT NULL DEFAULT 'PUBLIC';

CREATE TABLE post_readers (
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, user_id)
);
